# Generated by Django 5.0.4 on 2024-05-31 23:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foruns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira um genero pra posts de Forums', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpostcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumpostcomment',
            name='ForumPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foruns.forumpost'),
        ),
        migrations.AddConstraint(
            model_name='generoforum',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='generoForum_name_case_insensitive_unique', violation_error_message='Esse genero ja existe (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='genero',
            field=models.ForeignKey(help_text='Selecione o genero do seu post', null=True, on_delete=django.db.models.deletion.CASCADE, to='foruns.generoforum'),
        ),
    ]
