# Generated by Django 5.0.4 on 2024-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_genero_noticia_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('corpo', models.TextField(max_length=5000)),
            ],
        ),
    ]
