# Generated by Django 5.0.4 on 2024-05-31 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticiaweb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticiaweb',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='noticiaweb',
            name='link',
        ),
        migrations.AddField(
            model_name='noticiaweb',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='noticias.genero'),
        ),
    ]
